"""Fixup

Revision ID: b94ec736da4a
Revises: fb0d9328f639
Create Date: 2025-04-06 08:32:21.274693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94ec736da4a'
down_revision: Union[str, None] = 'fb0d9328f639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'power_hours_ats_record', ['date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'power_hours_ats_record', type_='unique')
    # ### end Alembic commands ###
